# Site settings
title:          Dalgun NOTE
description:    "PlayGround, Dalgun NOTE"
baseurl:        ""
url:            "https://dalgun.dev"

# Google Analytics
google_analytics: UA-102144136-1

# Author
author:
  name:         Dalgun
  url:          https://dalgun.dev
  email:        dalgun@icloud.com
  github:       dalgun
  instagram:    dalgoooooon

# Build settings
markdown:       kramdown


# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:  /blog/:year-:month-:day/:title


# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
disqus:         dalgun-1